name: ci
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    strategy:
      matrix:
        node-version: [14.x]
    services:
      mongo:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_INITDB_DATABASE: bridge-test
        ports:
          - 27017:27017
      bridge-redis:
        image: redis:latest
        ports:
          - 6379:6379

    env:
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
      NODE_ENV: development
      inxtbridge_storage__mongoUrl: mongodb://admin:password@localhost:27017/bridge-test
      inxtbridge_redis__host: localhost
      inxtbridge_storage__mongoOpts__dbName: bridge-test

      inxtbridge_api_keys__segment_test: WDeJ6fM5C79J7xikZOAiQYHwmUhFGOc3
      inxtbridge_application__CLUSTER__0: 9a1c78a507689f6f54b847ad1cef1e614ee23f1e
      inxtbridge_logger__level: 5
      inxtbridge_storage__mongoOpts__authSource: admin
      inxtbridge_stripe__PK_LIVE: pk_live_api_key
      inxtbridge_api_keys__segment: segment_key
      inxtbridge_stripe__SK_LIVE: sk_live_stripe_key
      inxtbridge_storage__mongoOpts__pass: password
      inxtbridge_redis__port: 6379
      inxtbridge_server__ssl__redirect: 443
      inxtbridge_redis__password:
      inxtbridge_complex__rpcUser: networkuser
      inxtbridge_stripe__SIG_TEST: stripe_sig_test
      inxtbridge_gateway__username: user
      inxtbridge_mailer__auth__pass: mailerpass
      inxtbridge_storage__mongoOpts__user: admin
      inxtbridge_stripe__PK_TEST: pk_test_vpHlkSQ7DhmzSW4EbmfT1lIJ
      #inxtbridge_storage__mongoOpts__replicaSet: internxt-net
      inxtbridge_complex__rpcPassword: networkpass
      inxtbridge_mailer__host: smtp.sendgrid.net
      inxtbridge_server__public__host: drive-server
      inxtbridge_stripe__SK_TEST: sk_test_stripe_key
      inxtbridge_complex__rpcUrl: http://landlord:8080
      inxtbridge_mailer__auth__user: internxt
      inxtbridge_mailer__sendgrid__api_key: APIKEY
      inxtbridge_storage__mongoOpts__server__poolSize: 100
      inxtbridge_stripe__SIG: whsec_otra_clave_de_stripe
      inxtbridge_drive__api: http://drive-server:8000
      inxtbridge_server__public__port: 443
      inxtbridge_mailer__port: 465
      inxtbridge_gateway__password: gatewaypass
      inxtbridge_gateway__JWT_SECRET: asecret
      inxtbridge_QUEUE_HOST: 100.100.100.100
      inxtbridge_QUEUE_USERNAME: username
      inxtbridge_QUEUE_PASSWORD: password

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2

      - run: yarn --ignore-engines
      - run: yarn run test
      - run: yarn run test-mongo-init
      - run: yarn run test-mongo
      - run: yarn run dev & yarn run test:e2e
