name: ci
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  test:
    runs-on: ubuntu-latest
    container: ubuntu
    permissions:
      contents: read
      packages: read
    strategy:
      matrix:
        node-version: [14.x]
    services:
      mongo:
        image: mongo:latest
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_INITDB_DATABASE: bridge-test
        ports:
          - 27017:27017
      bridge-redis:
        image: redis:latest
        ports:
          - 6379:6379

    env:
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
      NODE_ENV: development
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2

      - run: yarn --ignore-engines
      - run: yarn run test
      - run: yarn run test-mongo-init
      - run: yarn run test-mongo

      - name: build Bridge
        run: docker build . -t bridge
      - name: run bridge
        run: docker run -p 6382:6382 -e NODE_ENV=development -e inxtbridge_storage__mongoUrl=mongodb://admin:password@localhost:27017/bridge-test -e inxtbridge_redis__host=redis -d bridge
